version: '3.8'

services:
  redcap2sqlite:
    image: ghcr.io/im2neuroing/redcap2sqlite:main
    volumes:
      # folders to mount
      - ./DMS/:/app/DMS/
      # files to mount needed for the configuration
      - ./config_docker.json:/app/config.json:ro

      # (optional) mount the raw data csv file (if extraction is skipped - see example)
      - ./ClassicDB_example/rawdata/ClassicDatabase_DATA.csv:/app/setup/DATA.csv:ro
      # mount the entire mappingtables directory
      - ./ClassicDB_example/mappingtables:/app/setup/mappingtables:ro
      # mount the sqlite schema file
      - ./ClassicDB_example/sqlite_schema.sql:/app/setup/sqlite_schema.sql:ro
    environment:
      - PYTHONUNBUFFERED=1
